### ISSUE TITLE
/pt removed

### ISSUE THREAD

**Issue by nfacha** [plibither8/made-with-love-in#12]
https://github.com/plibither8/made-with-love-in/commit/9c6c662d4c31a301ec7899470c66d19068c7b9da

Why was this removed?
Can you provide static version of the image so it can be hosted somewhere else?

**Comment by plibither8** [comment]
Hi. I removed pt for now because someone was making thousands of requests to it every hours, exceeding the Vercel hobby plan's limits.

I'll upload a static version to this repo which you can directly use, or download and host elsewhere.

**Comment by plibither8** [comment]
Here it is: https://raw.githubusercontent.com/plibither8/made-with-love-in/master/static/pt.svg

**Comment by nfacha** [comment]
That might have been me actually since I added it to my website (with ~4M hits over the last 24h), it was not added just now tho, it was there for more than a month by now :sweat_smile:

I have removed it, so you can unlock it for other people if you want.
I'll host a static version on my side

Sorry :sweat_smile:

**Comment by plibither8** [comment]
Ahh alright! Thank you for fixing it up quickly :)

I'd like to know the website too, if you can tell me. 4M is a huge number and I'd want yo see how my little project contributed 😅.

**Comment by nfacha** [comment]
freemcserver.net
Was on the control panel footer, currently commented out tho
Next release will place the static version there

**Comment by plibither8** [comment]
Nice! Thanks for using this little service :)

**Comment by nfacha** [comment]
@plibither8 Just  to let you know that while the endpoint is enabled you forgot to re-enable Portugal from the generator dropdown :)

**Comment by plibither8** [comment]
Ahh damn, you're right! I'll do that asap. Thanks! :D
